name: QCSchema

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        conda-env: [base]
        python-version: [3.7]
    env:
      PYVER: ${{ matrix.python-version }}
      CONDA_ENV: ${{ matrix.conda-env }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: qcel

    - name: Checkout schema repo
      uses: actions/checkout@v2
      with:
        repository: MolSSI/QCSchema
        path: qcsk
        ref: qcsk_export_2
        #ref: master
        persist-credentials: false
        fetch-depth: 0

    - name: Python Setup
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Create Environment
      shell: bash
      working-directory: ./qcel
      run: |
        eval "$(conda shell.bash hook)" && conda activate
        python devtools/scripts/create_conda_env.py -n=test -p=$PYVER devtools/conda-envs/$CONDA_ENV.yaml

    - name: Install
      shell: bash
      working-directory: ./qcel
      run: |
        eval "$(conda shell.bash hook)" && conda activate test
        python -m pip install . --no-deps

    - name: Environment Information
      shell: bash
      run: |
        eval "$(conda shell.bash hook)" && conda activate test
        conda list --show-channel-urls

    - name: QCSchema from QCElemental
      shell: bash
      working-directory: ./qcel
      run: |
        eval "$(conda shell.bash hook)" && conda activate test
        make qcschema
        ls -l qcschema
        cp -p qcschema/* ../qcsk/qcschema/data/vdev/
        mv ../qcsk/qcschema/data/vdev/QCSchema.schema ../qcsk/qcschema/dev/

    - name: Compare Schemas (generated vs. community)
      shell: bash
      working-directory: ./qcsk
      run: |
        git diff --color-words
        pull_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
        branch=qcel-${pull_number}
        git checkout -b ${branch}
        git remote -v
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "auto-generated from QCElemental"
        echo "::set-env name=prbranch::${branch}"

    - name: Propose changes
      uses: ad-m/github-push-action@master
      with:
        directory: ./qcsk
        repository: MolSSI/QCSchema
        branch: ${{ env.prbranch }}
#        github_token: ${{ secrets.GITHUB_TOKEN }}
        github_token: ${{ secrets.qcschema_from_qcelemental }}
        force: true
